### ISSUE TITLE
Metadata for Quicklisp

### ISSUE THREAD

**Issue by hydandata** [mkoeppe/cl-bibtex#1]
Please consider adding :description, :author and :license information to your ASDF system(s). This will greatly help Quicklisp users and make it easier for them to report bugs.

More information:

http://blog.quicklisp.org/2015/05/looking-for-more-metadata.html
https://www.quicklisp.org

**Comment by mkoeppe** [comment]
I would accept a patch that does that.

On Sunday, May 31, 2015, David Chkhikvadze notifications@github.com wrote:

> Please consider adding :description, :author and :license information to
> your ASDF system(s). This will greatly help Quicklisp users and make it
> easier for them to report bugs.
> 
> More information:
> 
> http://blog.quicklisp.org/2015/05/looking-for-more-metadata.html
> https://www.quicklisp.org
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/mkoeppe/cl-bibtex/issues/1.

## 

Matthias Koeppe -- Professor -- http://www.math.ucdavis.edu/~mkoeppe

**Comment by mkoeppe** [comment]
Fixed in 17a16f5
